[tools]
terraform = "1.11.1"
terraform-docs = "0.19.0"
tflint = "0.55.1"

[tasks."terraform:init"]
description = "Validates the Terraform files"
run = "terraform init"
depends = ["terraform:init:vnet-link", "terraform:init:a-record", "terraform:init:data"]
dir = "{{ config_root }}"

[tasks."terraform:init:vnet-link"]
description = "Validates the Terraform files"
run = "terraform init"
dir = "{{ config_root }}/modules/vnet-link"

[tasks."terraform:init:a-record"]
description = "Validates the Terraform files"
run = "terraform init"
dir = "{{ config_root }}/modules/a-record"

[tasks."terraform:init:data"]
description = "Validates the Terraform files"
run = "terraform init"
dir = "{{ config_root }}/modules/data"

[tasks."terraform:validate"]
description = "Validates the Terraform files"
depends = ["terraform:validate:vnet-link", "terraform:validate:a-record", "terraform:validate:data", "terraform:init"]
run = "terraform validate"

[tasks."terraform:validate:vnet-link"]
description = "Validates the Terraform files"
depends = ["terraform:init:vnet-link"]
run = "terraform validate"
dir = "{{ config_root }}/modules/vnet-link"

[tasks."terraform:validate:a-record"]
description = "Validates the Terraform files"
depends = ["terraform:init:a-record"]
run = "terraform validate"
dir = "{{ config_root }}/modules/a-record"

[tasks."terraform:validate:data"]
description = "Validates the Terraform files"
depends = ["terraform:init:data"]
run = "terraform validate"
dir = "{{ config_root }}/modules/data"

[tasks."terraform:format"]
description = "Formats the Terraform files"
depends = ["terraform:format:a-record", "terraform:format:vnet-link", "terraform:format:data", "terraform:init"]
run = "terraform fmt"

[tasks."terraform:format:a-record"]
description = "Formats the Terraform files"
run = "terraform fmt"
dir = "{{ config_root }}/modules/a-record"

[tasks."terraform:format:vnet-link"]
description = "Formats the Terraform files"
run = "terraform fmt"

[tasks."terraform:format:data"]
description = "Formats the Terraform files"
run = "terraform fmt"


[tasks."tfdocs:generate"]
description = "Generates the Terraform documentation"
run = "terraform-docs markdown . > README.md"
depends = ["tfdocs:generate:a-record", "tfdocs:generate:vnet-link", "tfdocs:generate:data"]

[tasks."tfdocs:generate:a-record"]
description = "Generates the Terraform documentation"
dir = "{{ config_root }}/modules/a-record"
run = "terraform-docs markdown . > README.md"

[tasks."tfdocs:generate:vnet-link"]
description = "Generates the Terraform documentation"
dir = "{{ config_root }}/modules/vnet-link"
run = "terraform-docs markdown . > README.md"

[tasks."tfdocs:generate:data"]
description = "Generates the Terraform documentation"
dir = "{{ config_root }}/modules/data"
run = "terraform-docs markdown . > README.md"